name: Vue

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  vue-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
        run: npm install
      - name: Building the project
        run: npm run build
      - name: Sync
        env:
          dest: "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/vue-crud.zzidzz.tech/public"
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > ~/deploy_key
          chmod 600 ~/deploy_key
          rsync -chav --delete \
            -e 'ssh -i ~/deploy_key -o StrictHostKeyChecking=no' \
            --exclude ~/deploy_key \
            --exclude .git/ \
            --exclude .github/ \
            --exclude .env \
            --exclude vendor/ \
            ./dist/* ${{env.dest}}
